# Generated by Django 3.1.3 on 2020-11-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='departmant',
        ),
    ]
